substitutions:
  _PROJECT_ID: pointers-405713
  _BACKEND_IMAGE: gcr.io/pointers-405713/pointers_backend
  _FRONTEND_IMAGE: gcr.io/pointers-405713/pointers_frontend

steps:
  # Build the backend (Java)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "cd backend_pointers && gcloud builds submit --tag $_BACKEND_IMAGE",
      ]

  # Build the frontend (React)
  - name: "node:20.3.1" # or whichever node version you are using
    entrypoint: "bash"
    args: ["-c", "cd frontend_pointers && npm install && npm run build"]

# Images to be built by this configuration
images:
  - "$_BACKEND_IMAGE"
  - "$_FRONTEND_IMAGE"
