steps:
  # Build the backend (Java)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "cd backend_pointers && gcloud builds submit --pack image=gcr.io/$PROJECT_ID/my-app-backend",
      ]

  # Build the frontend (React)
  - name: "node:20.3.1" # or whichever node version you are using
    entrypoint: "bash"
    args: ["-c", "cd frontend_pointers && npm install && npm run build"]

  # Optional: If you need to containerize your React app
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-app-frontend", "."]
    dir: "frontend/build"

# Images to be built by this configuration
images:
  - "gcr.io/$PROJECT_ID/my-app-backend"
  - "gcr.io/$PROJECT_ID/my-app-frontend"
